POST http://20.244.56.144/evaluation-service/auth
Content-Type: application/json

{
  "email": "cs22b1096@iiitdm.ac.in",
  "name": "pratyek thumula",
  "rollNo": "cs22b1096",
  "accessCode": "wcHHrp",
  "clientID": "a68f3a0c-8510-4553-84c3-367a6f22ddce",
  "clientSecret": "PBzVDmqFTCrdaPfs"
}

###GET 
GET http://20.244.56.144/evaluation-service/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZXhwIjoxNzQ1MTI3OTc3LCJpYXQiOjE3NDUxMjc2NzcsImlzcyI6IkFmZm9yZG1lZCIsImp0aSI6ImE2OGYzYTBjLTg1MTAtNDU1My04NGMzLTM2N2E2ZjIyZGRjZSIsInN1YiI6ImNzMjJiMTA5NkBpaWl0ZG0uYWMuaW4ifSwiZW1haWwiOiJjczIyYjEwOTZAaWlpdGRtLmFjLmluIiwibmFtZSI6InByYXR5ZWsgdGh1bXVsYSIsInJvbGxObyI6ImNzMjJiMTA5NiIsImFjY2Vzc0NvZGUiOiJ3Y0hIcnAiLCJjbGllbnRJRCI6ImE2OGYzYTBjLTg1MTAtNDU1My04NGMzLTM2N2E2ZjIyZGRjZSIsImNsaWVudFNlY3JldCI6IlBCelZEbXFGVENyZGFQZnMifQ.Q8zqL8Dq0SzkQgbs6ziCtO5NlfH_Bp_Ta-f5LPY6tX4
Content-Type: application/json

### Get Posts for a specific user (user ID 1)
GET http://20.244.56.144/evaluation-service/users/1/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZXhwIjoxNzQ1MTI3OTc3LCJpYXQiOjE3NDUxMjc2NzcsImlzcyI6IkFmZm9yZG1lZCIsImp0aSI6ImE2OGYzYTBjLTg1MTAtNDU1My04NGMzLTM2N2E2ZjIyZGRjZSIsInN1YiI6ImNzMjJiMTA5NkBpaWl0ZG0uYWMuaW4ifSwiZW1haWwiOiJjczIyYjEwOTZAaWlpdGRtLmFjLmluIiwibmFtZSI6InByYXR5ZWsgdGh1bXVsYSIsInJvbGxObyI6ImNzMjJiMTA5NiIsImFjY2Vzc0NvZGUiOiJ3Y0hIcnAiLCJjbGllbnRJRCI6ImE2OGYzYTBjLTg1MTAtNDU1My04NGMzLTM2N2E2ZjIyZGRjZSIsImNsaWVudFNlY3JldCI6IlBCelZEbXFGVENyZGFQZnMifQ.Q8zqL8Dq0SzkQgbs6ziCtO5NlfH_Bp_Ta-f5LPY6tX4
Content-Type: application/json

### Get Posts (Latest)
GET http://20.244.56.144/evaluation-service/posts?type=latest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZXhwIjoxNzQ1MTI3OTc3LCJpYXQiOjE3NDUxMjc2NzcsImlzcyI6IkFmZm9yZG1lZCIsImp0aSI6ImE2OGYzYTBjLTg1MTAtNDU1My04NGMzLTM2N2E2ZjIyZGRjZSIsInN1YiI6ImNzMjJiMTA5NkBpaWl0ZG0uYWMuaW4ifSwiZW1haWwiOiJjczIyYjEwOTZAaWlpdGRtLmFjLmluIiwibmFtZSI6InByYXR5ZWsgdGh1bXVsYSIsInJvbGxObyI6ImNzMjJiMTA5NiIsImFjY2Vzc0NvZGUiOiJ3Y0hIcnAiLCJjbGllbnRJRCI6ImE2OGYzYTBjLTg1MTAtNDU1My04NGMzLTM2N2E2ZjIyZGRjZSIsImNsaWVudFNlY3JldCI6IlBCelZEbXFGVENyZGFQZnMifQ.Q8zqL8Dq0SzkQgbs6ziCtO5NlfH_Bp_Ta-f5LPY6tX4
Content-Type: application/json

### Get Posts (Popular)
GET http://20.244.56.144/evaluation-service/posts?type=popular
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZXhwIjoxNzQ1MTI3OTc3LCJpYXQiOjE3NDUxMjc2NzcsImlzcyI6IkFmZm9yZG1lZCIsImp0aSI6ImE2OGYzYTBjLTg1MTAtNDU1My04NGMzLTM2N2E2ZjIyZGRjZSIsInN1YiI6ImNzMjJiMTA5NkBpaWl0ZG0uYWMuaW4ifSwiZW1haWwiOiJjczIyYjEwOTZAaWlpdGRtLmFjLmluIiwibmFtZSI6InByYXR5ZWsgdGh1bXVsYSIsInJvbGxObyI6ImNzMjJiMTA5NiIsImFjY2Vzc0NvZGUiOiJ3Y0hIcnAiLCJjbGllbnRJRCI6ImE2OGYzYTBjLTg1MTAtNDU1My04NGMzLTM2N2E2ZjIyZGRjZSIsImNsaWVudFNlY3JldCI6IlBCelZEbXFGVENyZGFQZnMifQ.Q8zqL8Dq0SzkQgbs6ziCtO5NlfH_Bp_Ta-f5LPY6tX4
Content-Type: application/json

### Get Comments for a Post (post ID 150)
GET http://20.244.56.144/evaluation-service/posts/973/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZXhwIjoxNzQ1MTI3OTc3LCJpYXQiOjE3NDUxMjc2NzcsImlzcyI6IkFmZm9yZG1lZCIsImp0aSI6ImE2OGYzYTBjLTg1MTAtNDU1My04NGMzLTM2N2E2ZjIyZGRjZSIsInN1YiI6ImNzMjJiMTA5NkBpaWl0ZG0uYWMuaW4ifSwiZW1haWwiOiJjczIyYjEwOTZAaWlpdGRtLmFjLmluIiwibmFtZSI6InByYXR5ZWsgdGh1bXVsYSIsInJvbGxObyI6ImNzMjJiMTA5NiIsImFjY2Vzc0NvZGUiOiJ3Y0hIcnAiLCJjbGllbnRJRCI6ImE2OGYzYTBjLTg1MTAtNDU1My04NGMzLTM2N2E2ZjIyZGRjZSIsImNsaWVudFNlY3JldCI6IlBCelZEbXFGVENyZGFQZnMifQ.Q8zqL8Dq0SzkQgbs6ziCtO5NlfH_Bp_Ta-f5LPY6tX4
Content-Type: application/json